Payrolls/Models/Allowance.cs
namespace Payrolls.Models
{
    public class Allowance
    {

        public int AllowanceId { get; set; }    

        public string AllowanceName { get; set; }   

        public string AllowanceCode { get; set; }   

        public bool IsActive { get; set; }
       public DateTime createddate { get; set; }   

    }
}

Payrolls/Models/ErrorViewModel.cs
namespace Payrolls.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Payrolls/Models/UserGroup.cs
namespace Payrolls.Models
 
{
    public class UserGroup
    {
        public int UserGroupId { get; set; }
        public string UserGroupName { get; set; }

        public string UserGroupCode { get; set; }

        public bool IsActive { get; set; }    

        public DateTime createddate { get; set; }


    }
}

Payrolls/Controllers/AllowanceController.cs
using Microsoft.AspNetCore.Mvc;
using Payrolls.DAO;

namespace Payrolls.Controllers
{
    public class AllowanceController : Controller
    {
        ApplicationDbContext _context;
        public AllowanceController(ApplicationDbContext context)
        {
            _context = context; 

        }
        public IActionResult Index()
        {



            return View();
        }
    }
}

Payrolls/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Payrolls.Models;

namespace Payrolls.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Payrolls/Controllers/UserGroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using Payrolls.DAO;
using Payrolls.Models;

namespace Payrolls.Controllers
{
    public class UserGroupController : Controller
    {
        ApplicationDbContext _context;
        public UserGroupController(ApplicationDbContext context) 
        {
                       _context= context;
        }

        public IActionResult Index()
        {
            List<UserGroup>data =_context
                .UserGroups
                .Where(x => x.IsActive == true)
                .ToList();

            return View(data);
        }

        [HttpPost]
        public JsonResult Create([FromBody] UserGroup model)
        {
            if (model.UserGroupId == 0)
            {
                // INSERT
                _context.UserGroups.Add(new UserGroup
                {
                    UserGroupName = model.UserGroupName,
                    UserGroupCode = model.UserGroupCode,
                    IsActive = true,
                    createddate = DateTime.Now
                });

                _context.SaveChanges();

                return Json(new { success = true, message = "Saved successfully" });
            }
            else
            {
                // UPDATE
                var existing = _context.UserGroups
                                       .FirstOrDefault(x => x.UserGroupId == model.UserGroupId);

                if (existing == null)
                    return Json(new { success = false, message = "Data not found" });

                existing.UserGroupName = model.UserGroupName;
                existing.UserGroupCode = model.UserGroupCode;

                _context.SaveChanges();

                return Json(new { success = true, message = "Updated successfully" });
            }
        }


        //========= to load data in table========== 
        [HttpGet]
        public JsonResult GetActiveUserGroups(string groupName,string groupCode, int UserGroupId)
        {
            List<UserGroup> ug = _context
                              .UserGroups
                                    
                                    .Where(x => x.IsActive == true
                                    && (UserGroupId == 0 || x.UserGroupId == UserGroupId)
                                    && (string.IsNullOrEmpty(groupName) || x.UserGroupName.Contains(groupName))
                                    && (string.IsNullOrEmpty(groupCode) || x.UserGroupCode.Contains(groupCode))
                                    )

                                    .ToList();




            return Json(ug);
        }



        [HttpGet]
        public JsonResult GetItemById(int id)
        {
            UserGroup row = _context
                        .UserGroups
                        .Where(x => x.UserGroupId == id)
                        .FirstOrDefault();
            if (row == null)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Data not found in Database!!!"
                });
            }
            else
            {
                return Json(new
                {
                    Success = true,
                    Message = "",
                    Data = row
                });
            }
        }

        //=====delete
        [HttpGet]
        public JsonResult DeleteUserGroup(int id)
        {
            var existingRow = _context
                                .UserGroups
                                .Where(x => x.UserGroupId == id)
                                .FirstOrDefault();
            if (existingRow == null)
            {
                return Json(new
                {
                    success = false,
                    Message = "Data Not Found in Database!"
                });
            }
            else
            {
                //HARD DELETE
                //_context.UserGroup.Remove(existingRow);
                //_context.SaveChanges();


                //SOFT DELETE
                existingRow.IsActive = false;
                _context.SaveChanges();

                return Json(new
                {
                    success = true,
                    Message = "Data Deleted Successfully"
                });
            }
        }



    }
}

Payrolls/Views/Allowance/Index.cshtml
@model IEnumerable<Payrolls.Models.Allowance>;

    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>AllowanceId</th>
                                <th>Name</th>
                                <th>AllowanceCode</th>
                                <th>IsActive</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.AllowanceId</td>
                                    <td>@item.AllowanceName</td>
                                    <td>@item.AllowanceCode</td>
                                    <td>@item.IsActive</td>
                                </tr>
                            }
                        </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>

Payrolls/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Payrolls/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Payrolls</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.3.7/css/dataTables.dataTables.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Payrolls.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">

    <!-- DataTables Buttons CSS (for copy, CSV, Excel, PDF, Print) -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Payrolls</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Payrolls - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js" integrity="sha512-eYSzo+20ajZMRsjxB6L7eyqo5kuXuS2+wEbbOkpaur+sA2shQameiJiWEzCIDwJqaB0a4a6tCuEvCOBHUg3Skg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <!-- jQuery (required by DataTables) -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <!-- DataTables Buttons JS -->
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.flash.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>

    <!-- Optional: JSZip for Excel export -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

    <!-- Optional: pdfmake for PDF export -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
                toastr.options = {
          "closeButton": true,
          "debug": false,
          "newestOnTop": false,
          "progressBar": false,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
    </script>

</body>
</html>

Payrolls/Views/UserGroup/Index.cshtml
@model IEnumerable<Payrolls.Models.UserGroup>;



    <div class="row mb-2">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <label>UserGroupName</label>
                            <input type="text" class="form-control txtSearchUserGroupName " />
                        </div>

                    <div class="col-md-4">
                        <label>UserGroupCode</label>
                        <input type="text" class="form-control txtSearchUserGroupCode " />
                    </div>

                    <div class="col-md-4"><br />
                       <button type="button" class="btn btn-success btnSearch">Search</button>
                    </div>

                    </div>
                </div>
             </div>
        </div>
    </div>


  <div class="row">
      <div class="col-md-6">
          <div class="card">
              <div class="card-body">
                
                <table class="table table-hover table-striped tblSetup ">
                    <thead>
                        <tr>
                            <th>SN</th>
                            
                            <th>UserGroupName</th>
                            <th>UserGroupCode</th>
                            <th>Action</th>
                            
                        </tr>
                       </thead>
                     
                    <tbody class="main-data">

                           
                       </tbody>

                </table>

              </div>
          </div>
      </div>

      <div class="col-md-4">
          <div class="card">
              <div class="card-body">
                  <div class="row">
                      <div class="col-md-12">
                          <label>UserGroupName</label><br />
                          <input type="text" class="form-control txtUserGroupName" />
                      </div>

                    <div class="col-md-12">
                        <label>UserGroupCode</label><br />
                        <input type="text" class="form-control txtUserGroupCode" />

                    </div>

                    <div class="col-md-12 mt-3">
                       <button type="button" class="btn btn-success btnsave">Save</button>
                       <button type="button" class="btn btn-danger btncancel">Cancel</button>
                        <input type="hidden" value="0" class="hdnId" />

                    </div>


                  </div>
              </div>
</div>
      </div>
  </div>


@section scripts {
    <script>
        $(document).ready(function(){
            loadData();
        });

        $(document).on('click', '.btncancel', function () {

            var ok = confirm("Are you sure to cancel the form..?");
            if(ok == true){

                clearForm();
            }
        });

        function clearForm() {
            $('.txtUserGroupName').val('');
            $('.txtUserGroupCode').val('');
             $('.hdnId').val('0');
        }

        $(document).on('click', '.btnsave', function () {

            var xyz = {
                UserGroupName: $('.txtUserGroupName').val(),
                UserGroupCode: $('.txtUserGroupCode').val(),
               UserGroupId: parseInt($('.hdnId').val()) || 0
            };

            if(xyz.UserGroupName == ''){

                toastr["error"]("please fill the usergroup name .....!");
            }
            else if(xyz.UserGroupCode == ''){
                toastr["error"]("please fill the usergroup code .....!");
            }
            else {
                $.ajax({
                    type: 'POST',
                    contentType:'application/json; charset=utf-8',
                    url: '@Url.Action("Create", "UserGroup")',
                    data: JSON.stringify(xyz),
                    success: function(abc){
                        toastr["success"](abc.message );

                        clearForm();
                        loadData();
                    },
                    error: function(){
                        toastr["error"]("data not send", "error");
                    }
                });
            }

        });

        // =========load data in table=======

        function loadData() {
            var xyz = {
                groupName: $('.txtSearchUserGroupName').val(),
                groupCode: $('.txtSearchUserGroupCode').val(),
            };
            $.ajax({
                method: 'get',
                contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("GetActiveUserGroups", "UserGroup")?groupName='+xyz.groupName +'&groupCode=' + xyz.groupCode,
                success: function (abc) {
                    var htmls = '';
                    $.each(abc, function (index, item) {
                        htmls += '<tr>';
                        htmls += '<td>' + (index + 1) + '</td>';
                        // htmls += '<td>' + item.userGroupId + '</td>';
                        htmls += '<td>' + item.userGroupName + '</td>';
                        htmls += '<td>' + item.userGroupCode + '</td>';
                       
                        htmls += '<td><button style="margin-right:5px;" class="btn btn-secondary btn-sm btnEdit" data-key="' + item.userGroupId + '"><i class="fa fa-edit"></i>EDIT</button><button class="btn btn-danger btn-sm btnDelete" data-key="' + item.userGroupId + '"><i class="fa fa-trash"></i>DELETE</button></td>';
                        htmls += '</tr>';
                    });

                    $('.main-data').html(htmls);

                   $('.tblSetup').DataTable({
                             dom: 'Bfrtip',                // This is required for buttons
                      buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
                     });

                },
                beforeSend: function () {
                    //$.blockUI();
                },
                complete: function () {
                    //$.unblockUI();
                }
            });
        }


        // =========edit=========

          $(document).on('click', '.btnEdit', function () {
            var key = $(this).data('key');
            $.ajax({
                methodType: 'get',
                content: '',
                url: '@Url.Action("GetItemById", "UserGroup")?id=' + key,
                success: function (abc) {
                    if (abc.success == true) {
                        $('.txtUserGroupName').val(abc.data.userGroupName);
                        $('.txtUserGroupCode').val(abc.data.userGroupCode);
                        $('.hdnId').val(abc.data.userGroupId);

                    } else {
                        toastr["error"](abc.message, "ERROR")
                    }
                },
                error: function () {

                },
                beforeSend: function () {
                    //$.blockUI();
                },
                complete: function () {
                    //$.unblockUI();
                }


            });
        })
        // =======delete
          $(document).on('click','.btnDelete',function(){

           var xyz=confirm("are you sure to delete the data.?")
           if (xyz == true)
         {

            var key=$(this).data('key');

             $.ajax({
                methodType: 'get',
                    content: 'application/json; charset=utf-8',
                    url: '@Url.Action("DeleteUserGroup", "UserGroup")?id=' + key,
                    success: function (abc) {
                        if (abc.success) {
                            toastr["success"](abc.message)
                            loadData();
                        } else {
                            toastr["error"](abc.message, "ERROR")
                        }
                    },
                    error: function () {

                    },
                    beforeSend: function () {
                        //$.blockUI();
                    },
                    complete: function () {
                        //$.unblockUI();
                    }
                });

             
           }
        });


        $(document).on('click','.btnSearch',function(){
            loadData();

        })



    </script>
}